version: '3.9'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mytrackingwallet
    security_opt:
      - label:disable
    volumes:
      - ./db-data/:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    security_opt:
      - label:disable
    volumes:
      # caso dê erro de permissão (fedora):
      # sudo chown -R 5050:5050 pgadmin
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      -  database